"""Add departure point and finish point field in Intervals

Revision ID: 2d15823972a4
Revises: e100244b860f
Create Date: 2024-03-22 11:43:11.995353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d15823972a4'
down_revision: Union[str, None] = 'e100244b860f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intervals', sa.Column('departure_point', sa.String(), nullable=True))
    op.add_column('intervals', sa.Column('finish_point', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('intervals', 'finish_point')
    op.drop_column('intervals', 'departure_point')
    # ### end Alembic commands ###
