"""Add is_selected field in Intervals

Revision ID: 99ace4b52216
Revises: 338997ebbe8c
Create Date: 2024-03-22 10:32:26.105246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99ace4b52216'
down_revision: Union[str, None] = '338997ebbe8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intervals', sa.Column('is_selected', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('intervals', 'is_selected')
    # ### end Alembic commands ###
